#!/bin/bash
# Copyright (c) 2011, Vít Šesták
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
# 
#     Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#     Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

name="install-play"
function usage {
	echo "usage:"
	echo "$name <play-version> # download a specific version"
	echo "$name # download the last version"
	echo "$name -h # help"
	echo "$name -help # help"
	echo "$name --help # help"
	echo "$name -s # status"
	echo "$name -status # status"
	echo "$name --status # status"
}

# process arguments
case $# in
	0 )
		version=$(
			wget -q -O - http://www.playframework.org/download |
			grep -o 'The latest official version is .*</strong>' |
			sed 's/The latest official version is <strong>\(.*\)<\/strong>/\1/g'
		)
		;;
	1 )
		case "$1" in
			-h|--help|-help )
				usage
				exit
				;;
			-s|-status|--status )
				echo "Play! directory: $PLAY_DIR"
				echo "Play! versions:"
				ls "$PLAY_DIR" | grep 'play-' | sed 's/play-/ * /'
				echo -n "Python version: "
				if [ "$PLAY_PYTHON_VERSION" == "" ]; then
					echo "default"
				else
					echo -n "$PLAY_PYTHON_VERSION"
					if echo '' | env "python$PLAY_PYTHON_VERSION" &> /dev/null; then
						echo " (exists)"
					else
						echo " (MISSING!)"
					fi
				fi
				exit
				;;
			*)
				version="$1"
		esac
		;;
	*)
		echo "ERROR: too much arguments"
		usage
		exit 5
		;;
esac

if [ "$PLAY_DIR" == "" ]; then
	echo 'Set $PLAY_DIR, please.'
	echo "You can use set-play-dir."
	exit 1
fi

####################
url="http://download.playframework.org/releases/play-$version.zip"
file="$(mktemp)"
dir="$PLAY_DIR/play-$version"
current_version_file="$PLAY_DIR/current.version"

if [ -e "$dir" ]; then
	echo "You've already installed Play $version."
	exit 4
fi

echo "Downloading Play! $version..."
if wget -O "$file" "$url"; then
	echo "Unzipping Play! $version..."
	if unzip -q "$file" -d "$PLAY_DIR"; then
		if [ "$PLAY_PYTHON_VERSION" != "" ]; then
			echo "Patching for Python $PLAY_PYTHON_VERSION..."
			env_hashbang_base='#!\/usr\/bin\/env'
			sed -i "s/$ENV_HASHBANG_BASE python/$ENV_HASHBANG_BASE python$PLAY_PYTHON_VERSION/" "$dir/play"
		else
			echo "Leaving the default Python version. If you have Python related problems, you should set \$PLAY_PYTHON_VERSION."
		fi
		echo "Cleaning..."
		rm "$file"
		if [ "$(uname -o)" != "Cygwin" ]; then
			rm "$dir/play.bat"
			rm -r "$dir/python"
		fi
		echo "Done."
		b="nothing"
		while [ "$b" != "y" -a "$b" != "n" -a "$b" != "" ];do
			echo -n "Set this version as default? [Y/n] "
			read b
		done
		if [ "$b" == "y" ] || [ "$b" == "" ]; then
			if echo -n "$version" > "$current_version_file"; then
				echo "OK, the default Play! version has been updated to $version."
			else
				echo "Updating Play! default version failed."
			fi
		else
			echo "OK, the default Play! version is unchanged."
		fi
		echo "You can update it in the following file: $current_version_file"
	else
		echo "Unzip failed!"
		exit 3
	fi
else
	echo Download failed!
	exit 2
fi
